refactor: move agent-db into new template
MapColonies/discrete-agent-db pull request #1
Opened 2022-07-04 13:41 UTC by ronenkapelian

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2022-07-04 16:36 UTC, asafMasa requested changes
👍

2022-07-04 16:36 UTC, asafMasa commented on config/custom-environment-variables.json
> +    "port": "DB_PORT",
"__format": "number"

2022-07-04 16:36 UTC, asafMasa commented on helm/templates/_helpers.tpl
> +{{- else -}}
is this a bug in boiler plate? if it is open PR

2022-07-04 16:36 UTC, asafMasa commented on tests/integration/layerHistory/layerHistory.spec.ts
> +      expect(findOneMock).toHaveBeenCalledWith(findRequest);
add  expect(response).toSatisfyApiSpec(); to each integration test

2022-07-05 07:37 UTC, ronenkapelian commented on config/custom-environment-variables.json
> +    "port": "DB_PORT",
resolve: changed to object with "__format": "number" field

2022-07-05 07:38 UTC, ronenkapelian commented on helm/templates/_helpers.tpl
> +{{- else -}}
not bug,
but another bug was discovered and had been fixed

2022-07-05 07:39 UTC, ronenkapelian commented on tests/integration/layerHistory/layerHistory.spec.ts
> +      expect(findOneMock).toHaveBeenCalledWith(findRequest);
added to all integration tests and was validated - open API was updated too satisfy the tests

2022-07-05 08:28 UTC, asafMasa approved these changes

2022-07-05 08:32 UTC, merged