chore: add helm chart to project
MapColonies/discrete-agent-db pull request #43
Opened 2022-03-10 12:26 UTC by AnguIar

2022-03-10 13:37 UTC, asafMasa approved these changes

2022-03-13 06:28 UTC, cl-shaharshavit-rnd requested changes

2022-03-13 06:28 UTC, cl-shaharshavit-rnd commented on config/custom-environment-variables.json
> +    "logging": {
revert - db logging isnt bolean.
the possibale values includes "true" and "false" but also "query", "error", "schema", "info", "log", "all"

2022-03-13 06:28 UTC, cl-shaharshavit-rnd commented on helm/values.yaml
> +  db:
move to "rasterCommon", eventually every shared config that isnt in the boilerplate should be there.

2022-03-13 06:28 UTC, cl-shaharshavit-rnd commented on helm/values.yaml
> +  db:
move to "rasterCommon". 
maybe apart from schema and logging? (for your consideration)

2022-03-15 13:10 UTC, cl-shaharshavit-rnd requested changes

2022-03-15 13:10 UTC, cl-shaharshavit-rnd commented on config/custom-environment-variables.json
> +    "enableSslAuth": "DB_SSL_ENABLE",
db sll enable is boolean

2022-03-16 10:08 UTC, merged